Repository bigscience-workshop/metadata, pull requests merged in 2022-04, with the labels that each got.

#139 build: sync setup.py defined dependencies and fix broken ones
  README.md
  poetry.lock
  pyproject.toml
  requirements-dev.txt
  requirements.txt
  requirements_resolved_with_extras_and_dev.txt
  setup.py
  tests/test_preprocessing_utils.py
Labels: bug

#128 feat: mark paragraphs by metadata-html #125
  bsmetadata/paragraph_by_metadata_html.py
  tests/test_get_paragraphs.py
  tests/test_preprocessing_utils.py
Labels: #paragraph_extraction

#144 Entity at paragraph level
  bsmetadata/preprocessing_utils.py
  tests/test_preprocessing_utils.py
Labels: #dataset
